numero = str(input('Informe um número: '))
print('Analisando o número {}'.format(numero))
print('Unidade: {}'.format(numero[3]))
print('Dezena:  {}'.format(numero[2]))
print('Centena: {}'.format(numero[1]))
print('Milhar:  {}'.format(numero[0]))
